/** Tailwind is used for layout utilities only. All colours, radii and fonts
 *  come from CSS variables in src/styles/tokens.css so a redesign only needs
 *  to touch that file (and components). */
/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        bg: 'var(--color-bg)',
        surface: 'var(--color-surface)',
        'surface-2': 'var(--color-surface-2)',
        section: 'var(--color-section)',
        'row-done': 'var(--color-row-done)',
        border: 'var(--color-border)',
        'border-control': 'var(--color-border-control)',
        'border-strong': 'var(--color-border-strong)',
        divider: 'var(--color-divider)',
        text: 'var(--color-text)',
        secondary: 'var(--color-text-secondary)',
        muted: 'var(--color-text-muted)',
        ghost: 'var(--color-text-ghost)',
        accent: 'var(--color-accent)',
        'accent-contrast': 'var(--color-accent-contrast)',
        'accent-soft': 'var(--color-accent-soft)',
        'accent-line': 'var(--color-accent-line)',
        'accent-tint': 'var(--color-accent-tint)',
        success: 'var(--color-success)',
        danger: 'var(--color-danger)',
        warning: 'var(--color-warning)',
        pr: 'var(--color-pr)',
        warmup: 'var(--color-warmup)',
        drop: 'var(--color-drop)',
        failure: 'var(--color-failure)',
        ss1: 'var(--color-superset-1)',
        ss2: 'var(--color-superset-2)',
        ss3: 'var(--color-superset-3)',
        ss4: 'var(--color-superset-4)',
        'heat-0': 'var(--heat-0)',
        'heat-1': 'var(--heat-1)',
        'heat-2': 'var(--heat-2)',
        'heat-3': 'var(--heat-3)',
        'heat-4': 'var(--heat-4)',
        'hint-up': 'var(--color-hint-up)',
        'hint-hold': 'var(--color-hint-hold)',
        'hint-down': 'var(--color-hint-down)',
      },
      borderRadius: { DEFAULT: 'var(--radius)', md: 'var(--radius-md)', lg: 'var(--radius-lg)' },
      fontFamily: { sans: 'var(--font-sans)' },
    },
  },
  plugins: [],
};
