// Public-domain photos + muscle data from free-exercise-db
// (https://github.com/yuhonas/free-exercise-db, Unlicense), generated by
// scripts/fetch-exercise-media.mjs. Thumbnails are precached for offline use;
// full photos are cached the first time they are viewed (see vite.config.ts).
import data from './exerciseMedia.generated.json';

export interface ExerciseMedia {
  /** Start and end position photos. */
  images: string[];
  thumb: string;
  primaryMuscles: string[];
  secondaryMuscles: string[];
}

type Raw = { images: number; primaryMuscles: string[]; secondaryMuscles: string[]; source: string };
const RAW = data as Record<string, Raw>;

export function mediaPath(exerciseId: string, file: string): string {
  return `${import.meta.env.BASE_URL}exercise-media/${exerciseId}/${file}`;
}

export function exerciseMedia(exerciseId: string): ExerciseMedia | undefined {
  const r = RAW[exerciseId];
  if (!r) return undefined;
  return {
    images: Array.from({ length: r.images }, (_, i) => mediaPath(exerciseId, `${i}.jpg`)),
    thumb: mediaPath(exerciseId, 'thumb.jpg'),
    primaryMuscles: r.primaryMuscles,
    secondaryMuscles: r.secondaryMuscles,
  };
}

export const MEDIA_EXERCISE_IDS = Object.keys(RAW);
